### ISSUE TITLE
PetDB Bug: Session expired error when select "Include samples with all selected variables" AND tag-along data

### ISSUE THREAD

**Issue by kelseymarkey** [iedadata/PetDB#1]
On September 19 a user (Ed Marshall) reported that he often got a session expiration error when he tried to download data on PetDB. After testing we found that the bug was related to a query with both: 1) 'Include samples with all selected variables' and 2) 'tag-along' data. 

To replicate: 
SAMPLE TYPE: CLASS: xenolith:DUNITE, xenolith:HARZBURGITE, xenolith:LHERZOLITE, xenolith: PERIDOTITE
MATERIAL: Rock analysis
One row per sample, include samples with all variables, include whole rock and glass analysis
Variables: Has Os, Ir, Ru, Rh, Pd, Pt, Re trace element analyses
59 results.
Include Major Oxides, Trace Elements, Isotope Ratios.

RT Ticket: http://request.ieda-admin.org/Ticket/Display.html?id=2832

The original response to this issue was version v2.9.3. This resulted in additional bugs (see http://jira.iedadata.org/browse/PET-384), so we rolled back to v2.9.2.

**Comment by kelseymarkey** [comment]
@lulin-song I still can't change the assignees/projects/labels/milestone for this ticket. I'm not sure why, since I have these permissions on other repositories (i.e. SESAR). Could you add these things for this ticket? Thanks!

**Comment by lulin-song** [comment]
@kelseymarkey Just made you 'Admin' of this repo. Let me know if permission is an issue. I also deployed a test version loadpetdb. Can you test it at the following site?
http://isotope.ldeo.columbia.edu:7001/loadpetdb/search/start

**Comment by kelseymarkey** [comment]
Thanks Lulin, permissions are all good now. I have added Annika as a collaborator and we will test this tomorrow.

**Comment by lulin-song** [comment]
@annikakj Can you test this when you have time? Thanks, LS

**Comment by annikakj** [comment]
I have tested this and the disabling of Tag-along works for this query

**Comment by lulin-song** [comment]
@annikakj Can you also check if the bugs described on JIRA PET-384 appear on this version? They should not. http://jira.iedadata.org/browse/PET Thanks, LS

**Comment by annikakj** [comment]
@Lulin: tried following search: Feature Name> Spreading Center > Knipovich Ridge>Rock Analyses> One row per sample>Include samples with one or more selected variables > Include whole rock and glass analyses >majors>(41 precompiled analyses)> download button does not work

**Comment by kelseymarkey** [comment]
@lulin-song the session expiration issue seems to have been fixed with the disabling of tag-along data when "Include samples with all selected variables" is selected. 

However, I am running into issues where the download button still does not resolve (JIRA PET-384). I have run into this twice, both when dealing with larger datasets.

To replicate:
Quick search Mantle Xenolith data.
One row per sample, Include samples with all selected variables, SiO2, TiO2, Al2O3

**Comment by lulin-song** [comment]
Found some code in master branch were not merged back to development. Now they are synced. I made another deployment.@kelseymarkey @annikakj  Please check again on the following. site. http://isotope.ldeo.columbia.edu:7001/loadpetdb/search/start

**Comment by annikakj** [comment]
I just re-did the Knipovich search and this one:
Quick search Mantle Xenolith data.
One row per sample, Include samples with all selected variables, SiO2, TiO2, Al2O3

I was able to download data for both searches.

Annika

**Comment by kelseymarkey** [comment]
I tested both of those searches and a few others and found no bugs. Please proceed.
