### ISSUE TITLE
PetDB data holding statistics re-implementation

### ISSUE THREAD

**Issue by lulin-song** [iedadata/PetDB#6]
* PetDB data holding statistics program is a Java program which connects to Oracle petdb database. So its statistics do not reflect the current ECDB data holdings. It needs to be re-implemented.
* New web service to retrieve the data holdings from ECDB database is located below. https://ecapi.earthchem.org/statistics/entitystatistics
* The quickest way to display data holding on EarthChem site is to add a PHP script in Drupal to display the number from above web service.
* The best method is to implement the web service client which displays the number in ECDB eco systems and iframe to Drupal.

**Comment by lulin-song** [comment]
The existing PetDB data holding vs ECDB data holding number below

| Current data holding Name | number | ECDB  data holding Name | number |
|------     | ------  |------ | ------|
References|  2,426 | citations | 2685 |
Samples |    92,631 | specimens | 101890|
Bulk rock data points | 1,206,494 | rock_values | 1354539 |
Minerals | 1,493,880 | mineral_values |1782739|
Volcanic glasses|  670,710 | volc_glass_values | 689958 |
Melt inclusions |   125,936 | inclusion_values | 191656 |
Total individual values |  3,497,555 | total_chem_values | 4019427|
Number of stations | 25,879 | stations | 28730 |

@klehnert55 @sparkji  The ECDB web service has the different labels for the data holdings. Please confirm the number/labels are matched as above. The numbers below only exist in ECDB data holding web service. Should we include those numbers in data holdings stats too?

"datasets":8483,
"expeditions":1959,
"ts":"2018-10-15T12:38:42.971Z"

**Comment by kelseymarkey** [comment]
@annikakj can probably weigh in on this as well. Do all of the /numbers/labels above seem to make sense/match?

**Comment by sparkji** [comment]
@lulin-song "ts" need not show up, but I think "datasets" and "expedition" should be included.

**Comment by annikakj** [comment]
Yes, the numbers look reasonable.

Annika

**Comment by lulin-song** [comment]
@kelseymarkey Please copy/paste the php code from https://github.com/iedadata/PetDB/blob/master/ecdbstats.php to Drupal PetDB data holding block. You can do it on the dev first. Let me know if you need any help.
I have left out 'datasets' and 'expedition' but we can add them easily later if @klehnert55 confirms that.

**Comment by kelseymarkey** [comment]
Updated on http://earthchem.org/about/holdings

Only change I made to the php code was to match the other text. I edited ul style line to be:

echo "<ul style=\"font-family:Open Sans, sans serif;font-size:13.5px; line-height: 120%;color:#666666;margin-top:1px;margin-bottom:1px;font-wight:400;\">";

**Comment by lulin-song** [comment]
@kelseymarkey Good Job! I turned off the PetDB data holding stats and SedDB data holding stats on isotope.

**Comment by lulin-song** [comment]
Done some time ago. Close
