### ISSUE TITLE
Update PetDB graph on IEDA page

### ISSUE THREAD

**Issue by kelseymarkey** [iedadata/PetDB#7]
The graph at this page needs to be updated: https://www.iedadata.org/community/usage/

Currently it is showing all time lows because the numbers do not include new PetDB statistics. We need to update this graph to include new PetDB statistics.

1) When old PetDB is shut down, the graph should be populated only by new PetDB statistics 
2) The old statistics should remain for everything before that date
3) Any months (December, January, February) where both old and new PetDB were operating should have statistics that represent usage by both systems.

Lulin says that if new PetDB web service has the same API it is easy to combine the old and new statistics into one plot.

**Comment by lulin-song** [comment]
@sparkji Can you implement a web service which will return the value as below for the ECDB. You can leave out unique_email field because we are using that now.
http://isotope.ldeo.columbia.edu:7001/petdbWeb/search/download_stat.jsp?start=2018-12-01&end=2019-02-01

**Comment by sparkji** [comment]
Will do.

**Comment by sparkji** [comment]
The API for download statistics has been added. Please check https://ecapi.earthchem.org/statistics/downloadstatistics?start=2018-12-01&end=2019-02-01
```xml
<STATISTICS type="DOWNLOAD">
  <RECORD>
    <YEAR>2018</YEAR>
    <MONTH>12</MONTH>
    <UNIQUE_IP>3</UNIQUE_IP>
    <UNIQUE_EMAIL>2</UNIQUE_EMAIL>
    <MONTHLY_DOWNLOAD>4</MONTHLY_DOWNLOAD>
  </RECORD>
  <RECORD>
    <YEAR>2019</YEAR>
    <MONTH>1</MONTH>
    <UNIQUE_IP>106</UNIQUE_IP>
    <UNIQUE_EMAIL>70</UNIQUE_EMAIL>
    <MONTHLY_DOWNLOAD>332</MONTHLY_DOWNLOAD>
  </RECORD>
</STATISTICS>
```

**Comment by lulin-song** [comment]
@sparkji When was the NEW ECDB Search released? LS

**Comment by sparkji** [comment]
In the middle of Nov.
Try this
https://ecapi.earthchem.org/statistics/downloadstatistics?start=2018-11-01&end=2019-03-01

**Comment by lulin-song** [comment]
> In the middle of Nov.
> Try this
> https://ecapi.earthchem.org/statistics/downloadstatistics?start=2018-11-01&end=2019-03-01

@sparkji Is there any Nov stats? The above does not return November stats.

**Comment by sparkji** [comment]
@lulin-song actually we advertise new search to users until Nov. 28, so there is no stats for Nov and fewer numbers for Dec.

**Comment by lulin-song** [comment]
@sparkji  Can you check the web service to return XML instead of 'String'? Maybe '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' missing in the returned string?
Thanks, LS

**Comment by lulin-song** [comment]
@kelseymarkey The plot is updated. I created a test plot URL here. https://test-ecl.earthchem.org/plot/PetDBStatsPlotView.php Please check.

**Comment by kelseymarkey** [comment]
@lulin-song this looks great! Please proceed.

**Comment by lulin-song** [comment]
Done.
